// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS("14.0"),
        .macOS("11.0"),
        .tvOS("14.0"),
        .visionOS("1.0"),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/SPMForge/MoltenVK/releases/download/1.4.1-alpha.49/MoltenVK-1.4.1-alpha.49.xcframework.zip",
            checksum: "2ddcebfc64b782bdf863cb0b69b3f0c9985de4df73476a594a8590d1d8aa4272"
        ),
    ]
)
