// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS("14.0"),
        .macOS("11.0"),
        .tvOS("14.0"),
        .visionOS("1.0"),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/SPMForge/MoltenVK/releases/download/1.4.2-alpha.23/MoltenVK-1.4.2-alpha.23.xcframework.zip",
            checksum: "069a116d44359b7c8491e070ec008d4a583a69b7450c6bef0fbe380ad285fbf1"
        ),
    ]
)
