// swift-tools-version: 6.0
// Generated by Scripts/SwiftPackage/render_package_manifest.py. Do not edit by hand.

import PackageDescription

let package = Package(
    name: "MoltenVK",
    platforms: [
        .iOS("14.0"),
        .macOS("11.0"),
        .tvOS("14.0"),
        .visionOS("1.0"),
    ],
    products: [
        .library(
            name: "MoltenVK",
            targets: ["MoltenVK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/SPMForge/MoltenVK/releases/download/1.4.1-alpha.32/MoltenVK-1.4.1-alpha.32.xcframework.zip",
            checksum: "04b0778aa6e31d416c2be64864ddf9ce28d8338ce84300e00c4d55ee6c203232"
        ),
    ]
)
